# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 19:43


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('isbn', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('dept_course', models.TextField(blank=True, null=True)),
                ('descript_raw', models.TextField(blank=True, null=True)),
                ('toc_raw', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookTopicInfo',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('isbn', models.TextField(blank=True, null=True)),
                ('descript_topic_count', models.IntegerField(blank=True, null=True)),
                ('toc_topic_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_topic_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DescriptBookTopic',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('isbn', models.TextField(blank=True, null=True)),
                ('topic_id', models.TextField(blank=True, null=True)),
                ('topic_distribution', models.TextField(blank=True, null=True)),
                ('topic_words', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'descript_book_topics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DescriptTopic',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('topic_words', models.TextField(blank=True, null=True)),
                ('book_count', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'descript_topics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TocBookTopic',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('isbn', models.TextField(blank=True, null=True)),
                ('topic_id', models.TextField(blank=True, null=True)),
                ('topic_distribution', models.TextField(blank=True, null=True)),
                ('topic_words', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'toc_book_topics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TocFreq',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('isbn', models.TextField(blank=True, null=True)),
                ('frequency', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'toc_freq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TocTopic',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('topic_words', models.TextField(blank=True, null=True)),
                ('book_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'toc_topics',
                'managed': False,
            },
        ),
    ]
