# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookDisplayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('course', models.TextField(blank=True, null=True)),
                ('associated_books', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'class_info',
                'managed': False,
            },
        ),
    ]
