# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookDisplayer', '0002_classinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TextField(blank=True, null=True)),
                ('alpha', models.TextField(blank=True, null=True)),
                ('beta', models.TextField(blank=True, null=True)),
                ('iterations', models.TextField(blank=True, null=True)),
                ('num_topics', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'model_info',
                'managed': False,
            },
        ),
    ]
